# Generated by Django 3.0.7 on 2020-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
